=== governmentbg/bpo-eservices/common-utils/ConfigurationXSD/src/main/xsd/countries/country-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  * $Id::                                                                       $
  *       . * .
  *     * RRRR  *    Copyright Â© 2012 OHIM: Office for Harmonization
  *   .   RR  R   .  in the Internal Market (trade marks and designs)
  *   *   RRR     *
  *    .  RR RR  .   ALL RIGHTS RESERVED
  *     * . _ . *
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:tm="http://www.tm-xml.org/XMLSchema/common" targetNamespace="http://www.example.org/country-configuration"
	xmlns="http://www.example.org/country-configuration"
	elementFormDefault="qualified">

	<xs:element name="countries">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="country" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="code" type="xs:string" use="required" />
								<xs:attribute name="isEU" type="xs:boolean" use="required" />
                                <xs:attribute name="partOfEEA" type="xs:boolean" use="required" />
								<xs:attribute name="isPriority" type="xs:boolean"
									use="required" />
								<xs:attribute name="isSeniority" type="xs:boolean"
									use="required" />
								<xs:attribute name="hasState" type="xs:boolean"
									use="required" />
								<xs:attribute name="hasStateInc" type="xs:boolean"
									use="required" />
								<xs:attribute name="enabled" type="xs:boolean" use="required" />
								<xs:attribute name="isRepresentative" type="xs:boolean"
									use="required" />
								<xs:attribute name="isApplicant" type="xs:boolean"
									use="required" />
								<xs:attribute name="isDesigner" type="xs:boolean"
											  use="required" />
								<xs:attribute name="isNonRegisteredTM" type="xs:boolean" use="optional" />
								<xs:attribute name="isParisConvention" type="xs:boolean" use="optional" />
								<xs:attribute name="isEarlierWellKnow" type="xs:boolean" use="optional" />
								<xs:attribute name="isForeignTMView" type="xs:boolean" use="optional" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== governmentbg/bpo-eservices/core/ConfigurationMgmt/ConfigurationServiceDAO/src/test/resources/conf/EM/countries.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ * SystemConfigurationServiceDao:: countries.xml 07/10/13 21:16 karalch $
  ~  * . * .
  ~  * * RRRR * Copyright Â© 2013 OHIM: Office for Harmonization
  ~  * . RR R . in the Internal Market (trade marks and designs)
  ~  * * RRR *
  ~  * . RR RR . ALL RIGHTS RESERVED
  ~  * * . _ . *
  -->

<countries xmlns="http://www.example.org/country-configuration"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.example.org/country-configuration country-configuration.xsd ">
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="" enabled="true"
             isRepresentative="true" isApplicant="true">selectBox.SELECT</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="AT" enabled="true"
             isRepresentative="true" isApplicant="true">country.AUSTRIA</country>
    <country isEU="true" partOfEEA="true" isPriority="false" isSeniority="false"
             hasState="false" hasStateInc="false" code="BE" enabled="true"
             isRepresentative="true" isApplicant="true">country.BELGIUM</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="BX" enabled="true"
             isRepresentative="false" isApplicant="false">country.BENELUX</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="BG" enabled="true"
             isRepresentative="true" isApplicant="true">country.BULGARIA</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="CY" enabled="true"
             isRepresentative="true" isApplicant="true">country.CYPRUS</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="CZ" enabled="true"
             isRepresentative="true" isApplicant="true">country.CZECH_REPUBLIC</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="DK" enabled="true"
             isRepresentative="true" isApplicant="true">country.DENMARK</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="EE" enabled="true"
             isRepresentative="true" isApplicant="true">country.ESTONIA</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="FI" enabled="true"
             isRepresentative="true" isApplicant="true">country.FINLAND</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="FR" enabled="true"
             isRepresentative="true" isApplicant="true">country.FRANCE</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="DE" enabled="true"
             isRepresentative="true" isApplicant="true">country.GERMANY</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="GR" enabled="true"
             isRepresentative="true" isApplicant="true">country.GREECE</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="HU" enabled="true"
             isRepresentative="true" isApplicant="true">country.HUNGARY</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="true" code="IE" enabled="true"
             isRepresentative="true" isApplicant="true">country.IRELAND</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="IT" enabled="true"
             isRepresentative="true" isApplicant="true">country.ITALY</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="LV" enabled="true"
             isRepresentative="true" isApplicant="true">country.LATVIA</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="LT" enabled="true"
             isRepresentative="true" isApplicant="true">country.LITHUANIA</country>
    <country isEU="true" partOfEEA="true" isPriority="false" isSeniority="false"
             hasState="false" hasStateInc="false" code="LU" enabled="true"
             isRepresentative="true" isApplicant="true">country.LUXEMBOURG</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="MT" enabled="true"
             isRepresentative="true" isApplicant="true">country.MALTA</country>
    <country isEU="true" partOfEEA="true" isPriority="false" isSeniority="false"
             hasState="false" hasStateInc="false" code="NL" enabled="true"
             isRepresentative="true" isApplicant="true">country.NETHERLANDS</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="PL" enabled="true"
             isRepresentative="true" isApplicant="true">country.POLAND</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="PT" enabled="true"
             isRepresentative="true" isApplicant="true">country.PORTUGAL</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="RO" enabled="true"
             isRepresentative="true" isApplicant="true">country.ROMANIA</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="SK" enabled="true"
             isRepresentative="true" isApplicant="true">country.SLOVAKIA</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="SI" enabled="true"
             isRepresentative="true" isApplicant="true">country.SLOVENIA</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="ES" enabled="true"
             isRepresentative="true" isApplicant="true">country.SPAIN</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="false" code="SE" enabled="true"
             isRepresentative="true" isApplicant="true">country.SWEDEN</country>
    <country isEU="true" partOfEEA="true" isPriority="true" isSeniority="true"
             hasState="false" hasStateInc="true" code="GB" enabled="true"
             isRepresentative="true" isApplicant="true">country.UNITED_KINGDOM</country>
    <country isEU="false" partOfEEA="false" isPriority="false" isSeniority="false"
             hasState="false" hasStateInc="false" code="AF" enabled="true"
             isRepresentative="false" isApplicant="true">country.AFGHANISTAN</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="AP" enabled="true"
             isRepresentative="false" isApplicant="false">country.ARIPO</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="AL" enabled="true"
             isRepresentative="false" isApplicant="true">country.ALBANIA</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="DZ" enabled="true"
             isRepresentative="false" isApplicant="true">country.ALGERIA</country>
    <country isEU="false" partOfEEA="false" isPriority="false" isSeniority="false"
             hasState="true" hasStateInc="false" code="AS" enabled="true"
             isRepresentative="false" isApplicant="true">country.AMERICAN_SAMOA</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="AD" enabled="true"
             isRepresentative="false" isApplicant="true">country.ANDORRA</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="AO" enabled="true"
             isRepresentative="false" isApplicant="true">country.ANGOLA</country>
    <country isEU="false" partOfEEA="false" isPriority="false" isSeniority="false"
             hasState="false" hasStateInc="false" code="AI" enabled="true"
             isRepresentative="false" isApplicant="true">country.ANGUILLA</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="AQ" enabled="true"
             isRepresentative="false" isApplicant="true">country.ANTARCTICA</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
             hasState="false" hasStateInc="false" code="AG" enabled="true"
             isRepresentative="false" isApplicant="true">country.ANTIGUA_AND_BARBUDA</country>
    <country isEU="false" partOfEEA="false" isPriority="true" isSeniority="false"
