=== governmentbg/bpo-eservices/common-utils/ConfigurationXSD/src/main/xsd/colour/colour-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  * $Id::                                                                       $
  *       . * .
  *     * RRRR  *    Copyright Â© 2012 OHIM: Office for Harmonization
  *   .   RR  R   .  in the Internal Market (trade marks and designs)
  *   *   RRR     *
  *    .  RR RR  .   ALL RIGHTS RESERVED
  *     * . _ . *
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/test/"
	targetNamespace="http://www.example.org/test/">

	<complexType name="colourlist">
		<sequence>
			<element name="country" type="string"></element>
			<element name="values" type="string" maxOccurs="unbounded"
				minOccurs="1"></element>
		</sequence>
	</complexType>

	<element name="colour">
		<complexType>
			<sequence>
				<element name="colourList" type="tns:colourlist" maxOccurs="unbounded"
				minOccurs="1"></element>
			</sequence>
		</complexType>
	</element>

</schema>

=== governmentbg/bpo-eservices/core/IntegrationTests/src/test/resources/DS/conf/FI/colour-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:colour xmlns:tns="http://www.example.org/test/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/test/ ../../../../../../../../../../../../configuration-xsd/src/main/xsd/colour/colour-configuration.xsd ">

	<colourList>
		<country>el</country>
		<values>Λευκό</values>
		<values>Μαύρο</values>
		<values>Μπλε</values>
		<values>Κόκκινο</values>
		<values>Πράσινο</values>
		<values>Γκρι</values>
		<values>Κίτρινο</values>
		<values>Πορτοκαλί</values>
		<values>Καφέ</values>
		<values>Σκούρο μπλε</values>
		<values>Γαλάζιο</values>
		<values>Χρυσαφί</values>
		<values>Ροζ</values>
		<values>Μωβ</values>
		<values>Ανοιχτό πράσινο</values>
		<values>Σκούρο πράσινο</values>
		<values>Μπεζ</values>
		<values>Ασημί</values>
		<values>Σκούρο γκρι</values>
		<values>Ανοιχτό γκρι</values>
		<values>Βioλετι</values>
		<values>Ανοικτό καφετί</values>
		<values>Αποχρώσεις του μπλε</values>
		<values>Τυρκουάζ</values>
		<values>Φούξια</values>
		<values>Σκούρο καφέ</values>
		<values>Γκρενά</values>
		<values>Μπορντό</values>
		<values>Μοβ</values>
		<values>Κυανό</values>
		<values>Φούξια</values>
		<values>Ώχρα</values>
		<values>Ναυτικό μπλε</values>
		<values>Γκρι</values>
		<values>Αποχρώσεις του πράσινου</values>
		<values>Γκρενά</values>
		<values>Κυανό</values>
		<values>Αποχρώσεις του γκρίζου</values>
		<values>Κρεμ</values>
		<values>Ανοικτό πορτοκαλί</values>
		<values>Σκούρο πορτοκαλί</values>
		<values>Ανοιχτό κίτρινο</values>
		<values>Αποχρώσεις του κίτρινου</values>
		<values>Ανοιχτό κόκκινο</values>
		<values>Αποχρώσεις του κόκκινου</values>
		<values>Μωβ</values>
		<values>Σκούρο κίτρινο</values>
		<values>Κίτρινο Χρυσαφί</values>
		<values>Σκούρο ροζ</values>
		<values>Μέση απόχρωση του μπλε</values>
		<values>Καστανέρυθρο</values>
		<values>Ανοιχτό ροζ</values>
		<values>Αποχρώσεις του καφέ</values>
		<values>Λαδί</values>
		<values>Αποχρώσεις του πορτοκαλί</values>
		<values>Σκούρο μωβ</values>
		<values>Κυανό</values>
		<values>Ναυτικό μπλε</values>
		<values>Χρυσό</values>
		<values>Ανθρακί</values>
		<values>Μπλε-τυρκουάζ</values>
		<values>Ανοιχτό πράσινο</values>
		<values>Χρώμα του μπρούντζου</values>
		<values>Ανοιχτό μωβ</values>
		<values>Χαλκός</values>
		<values>Αποχρώσεις του ροζ</values>
		<values>Λουλακι</values>
	</colourList>

	<colourList>
		<country>en</country>
		<values>White</values>
		<values>Black</values>
		<values>Blue</values>
		<values>Red</values>
		<values>Green</values>
		<values>Grey</values>
		<values>Yellow</values>
		<values>Orange</values>
		<values>Brown</values>
		<values>Dark blue</values>
		<values>Light blue</values>
		<values>Gold</values>
		<values>Pink</values>
		<values>Purple</values>
		<values>Light green</values>
		<values>Dark green</values>
		<values>Beige</values>
		<values>Silver</values>
		<values>Dark grey</values>
		<values>Light grey</values>
		<values>Violet</values>
		<values>Light brown</values>
		<values>Shades of blue</values>
		<values>Turquoise</values>
		<values>Magenta</values>
		<values>Dark brown</values>
		<values>Dark red</values>
		<values>Burgundy</values>
		<values>Lilac</values>
		<values>Sky blue</values>
		<values>Fuchsia</values>
		<values>Ochre</values>
		<values>Navy blue</values>
		<values>Gray</values>
		<values>Shades of green</values>
		<values>Deep red</values>
		<values>Cyan</values>
		<values>Shades of grey</values>
		<values>Cream</values>
		<values>Light orange</values>
		<values>Dark orange</values>
		<values>Light yellow</values>
		<values>Shades of yellow</values>
		<values>Light red</values>
		<values>Shades of red</values>
		<values>Mauve</values>
		<values>Dark yellow</values>
		<values>Golden yellow</values>
		<values>Dark pink</values>
		<values>Medium blue</values>
		<values>Maroon</values>
		<values>Light pink</values>
		<values>Shades of brown</values>
		<values>Olive green</values>
		<values>Shades of orange</values>
		<values>Dark purple</values>
		<values>Azure</values>
		<values>Navy</values>
		<values>Golden</values>
		<values>Anthracite</values>
		<values>Turquoise blue</values>
		<values>Lime green</values>
		<values>Bronze</values>
		<values>Light purple</values>
		<values>Copper</values>
		<values>Shades of pink</values>
		<values>Indigo</values>
	</colourList>

	<colourList>
		<country>fr</country>
		<values>Blanc</values>
		<values>Noir</values>
		<values>Bleu</values>
		<values>Rouge</values>
		<values>Vert</values>
		<values>Gris</values>
		<values>Jaune</values>
		<values>Orange</values>
		<values>Brun</values>
		<values>Bleu foncé</values>
		<values>Bleu clair</values>
		<values>Or</values>
		<values>Rose</values>
		<values>Violet</values>
		<values>Vert clair</values>
		<values>Vert foncé</values>
		<values>Beige</values>
		<values>Argent</values>
		<values>Gris foncé</values>
		<values>Gris clair</values>
		<values>Violet</values>
		<values>Brun clair</values>
		<values>Nuances de bleu</values>
		<values>Turquoise</values>
		<values>Magenta</values>
		<values>Marron foncé</values>
		<values>Rouge foncé</values>
		<values>Bordeau</values>
		<values>Lilas</values>
		<values>Bleu ciel</values>
		<values>Fuchsia</values>
		<values>Ocre</values>
		<values>Bleu marine</values>
		<values>Gris</values>
		<values>Nuances de vert</values>
		<values>Rouge foncé</values>
		<values>Cyan</values>
		<values>Nuances de gris</values>
		<values>Crème</values>
		<values>Orange clair</values>
		<values>Orange foncé</values>
		<values>Jaune clair</values>
		<values>Nuances de jaune</values>
		<values>Rouge clair</values>
		<values>Nuances de rouge</values>
		<values>Mauve</values>
		<values>Jaune foncé</values>
		<values>Jaune doré</values>
		<values>Rose foncé</values>
		<values>Bleu moyen</values>
		<values>Brun</values>
		<values>Rose clair</values>
		<values>Nuances de brun</values>
		<values>Vert olive</values>
		<values>Nuances d'orange</values>
		<values>Violet foncé</values>
		<values>Bleu</values>
		<values>Bleu marine</values>
		<values>Doré</values>
		<values>Anthracite</values>
		<values>Bleu turquoise</values>
		<values>Vert jaune</values>
		<values>Couleur bronze</values>
		<values>Mauve clair</values>
		<values>Cuivre</values>
		<values>Nuances de rose</values>
		<values>Indigo</values>
	</colourList>

	<colourList>
		<country>es</country>
		<values>Blanco</values>
		<values>Negro</values>
		<values>Azul</values>
		<values>Rojo</values>
		<values>Verde</values>
		<values>Gris</values>
		<values>Amarillo</values>
		<values>Naranja</values>
		<values>Marron</values>
		<values>Azul oscuro</values>
		<values>Azul claro</values>
		<values>Dorado</values>
		<values>Rosa</values>
		<values>Morado</values>
		<values>Verde claro</values>
		<values>Verde oscuro</values>
		<values>Beige</values>
		<values>Plata</values>
		<values>Gris oscuro</values>
		<values>Gris claro</values>
		<values>Violeta</values>
		<values>Marrón claro</values>
		<values>Degradado de azul</values>
		<values>Turquesa</values>
		<values>Magenta</values>
		<values>Marrón oscuro</values>
		<values>Granate</values>
		<values>Burdeos</values>
		<values>Lila</values>
		<values>Celeste</values>
		<values>Fucsia</values>
		<values>Ocre</values>
		<values>Azul marino</values>
		<values>Gris</values>
		<values>Degradado de verde</values>
		<values>Granate</values>
		<values>Cian</values>
		<values>Degradado de gris</values>
		<values>Color crema</values>
		<values>Naranja claro</values>
		<values>Naranja oscuro</values>
		<values>Amarillo claro</values>
		<values>Degradado de amarillo</values>
		<values>Rojo claro</values>
		<values>Degradado de rojo</values>
		<values>Malva</values>
		<values>Amarillo oscuro</values>
		<values>Amarillo dorado</values>
		<values>Rosa oscuro</values>
		<values>Azul medio</values>
		<values>Granate</values>
		<values>Rosa claro</values>
		<values>Degradado de marrón</values>
		<values>Verde oliva</values>
		<values>Degradado de naranja</values>
		<values>Morado oscuro</values>
		<values>Azul celeste</values>
		<values>Azul marino</values>
		<values>Dorado</values>
		<values>Antracita</values>
		<values>Azul turquesa</values>
		<values>Verde pálido</values>
		<values>Color bronce</values>
		<values>Púrpura claro</values>
		<values>Color cobre</values>
		<values>Degradado de rosa</values>
		<values>Añil</values>
	</colourList>

	<colourList>
		<country>it</country>
		<values>Bianco</values>
		<values>Nero</values>
		<values>Blu</values>
		<values>Rosso</values>
		<values>Verde</values>
		<values>Grigio</values>
		<values>Giallo</values>
		<values>Arancione</values>
		<values>Marrone</values>
		<values>Azzurro scuro</values>
		<values>Blu chiaro</values>
		<values>Oro</values>
		<values>Rosa</values>
		<values>Viola</values>
		<values>Verde chiaro</values>
		<values>Verde scuro</values>
		<values>Beige</values>
		<values>Argento</values>
		<values>Grigio scuro</values>
		<values>Grigio chiaro</values>
		<values>Viola</values>
		<values>Marrone chiaro</values>
		<values>Sfumature di blu</values>
		<values>Turchese</values>
		<values>Magenta</values>
		<values>Marrone scuro</values>
		<values>Granata</values>
		<values>Bordeaux</values>
		<values>Lilla</values>
		<values>Celeste</values>
		<values>Fucsia</values>
		<values>Ocra</values>
		<values>Blu marino</values>
		<values>Grigio</values>
		<values>Sfumature di verde</values>
		<values>Granata</values>
		<values>Ciano</values>
		<values>Scala di grigi</values>
		<values>Panna</values>
		<values>Arancione chiaro</values>
		<values>Arancione scuro</values>
		<values>Giallo chiaro</values>
		<values>Sfumature gialle</values>
		<values>Rosso chiaro</values>
		<values>Sfumature di rosso</values>
		<values>Malva</values>
		<values>Giallo scuro</values>
		<values>Giallo oro</values>
		<values>Rosa scuro</values>
		<values>Blu medio</values>
		<values>Bordeaux</values>
		<values>Rosa chiaro</values>
		<values>Sfumature di marrone</values>
		<values>Verde oliva</values>
