=== governmentbg/bpo-eservices/common-utils/ConfigurationXSD/src/main/xsd/designs/designViewTypes-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/designViewTypes-configuration" xmlns="http://www.example.org/designViewTypes-configuration" elementFormDefault="qualified">

	<xs:element name="designViewTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="designViewType" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="code" type="xs:string" use="required"/>
						<xs:attribute name="value" type="xs:string" use="required"/>
						<xs:attribute name="order" type="xs:int" use="required" />
						<!-- xs:attribute name="name" type="xs:string"  use="required"/ -->
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== governmentbg/bpo-eservices/conf/sp-fo/configuration/app-server/ds-efiling/conf/designViewTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<designViewTypes xmlns="http://www.example.org/designViewTypes-configuration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/designViewTypes-configuration designViewTypes-configuration.xsd ">
	
	<designViewType code="" value="selectBox.SELECT" order="0" />

	<designViewType code="General" value="view.type.general" order="1" />
	<designViewType code="Perspective" value="view.type.perspective" order="2" />
	<!-- designViewType code="Major view" value="view.type.major" / -->
	<!-- designViewType code="Rear view" value="view.type.rear" / -->
	<designViewType code="Front" value="view.type.front" order="3" />
	<designViewType code="Back" value="view.type.back" order="4" />
	<designViewType code="Left" value="view.type.left" order="5" />
	<designViewType code="Right" value="view.type.right" order="6" />
	<!-- designViewType code="Left view" value="view.type.left" / -->
	<!-- designViewType code="Right view" value="view.type.right" / -->
	<designViewType code="Top" value="view.type.top" order="7" />
	<designViewType code="Bottom" value="view.type.bottom" order="8" />
	<designViewType code="Partial" value="view.type.partial" order="9" />
	
</designViewTypes>
